"""Pydantic request/response models — the structured contract of the API."""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, Field, field_validator

# Customer ids are opaque handles; we accept only this shape and reject the
# rest. This is input validation, not authentication — see README limitations.
CUSTOMER_ID_PATTERN = re.compile(r"^cust_[0-9a-zA-Z]{3,16}$")
SESSION_ID_PATTERN = re.compile(r"^[0-9a-zA-Z_\-]{1,64}$")


class ChatRequest(BaseModel):
    """An inbound turn of conversation."""

    message: str = Field(min_length=1, max_length=2000, description="The user's message.")
    customer_id: str | None = Field(
        default=None,
        description="Signed-in customer. Required for account-specific questions.",
    )
    session_id: str | None = Field(
        default=None,
        description="Conversation id. Generated by the server when omitted.",
    )

    @field_validator("message")
    @classmethod
    def _message_not_blank(cls, value: str) -> str:
        text = value.strip()
        if not text:
            raise ValueError("message must not be blank")
        return text

    @field_validator("customer_id")
    @classmethod
    def _valid_customer_id(cls, value: str | None) -> str | None:
        if value is None or not value.strip():
            return None
        value = value.strip()
        if not CUSTOMER_ID_PATTERN.match(value):
            raise ValueError("customer_id must look like 'cust_001'")
        return value

    @field_validator("session_id")
    @classmethod
    def _valid_session_id(cls, value: str | None) -> str | None:
        if value is None or not value.strip():
            return None
        value = value.strip()
        if not SESSION_ID_PATTERN.match(value):
            raise ValueError("session_id may contain only letters, digits, '-' and '_'")
        return value


class ChatResponse(BaseModel):
    """The assistant's structured reply."""

    answer: str = Field(description="The user-facing answer. Always safe to display.")
    tools_used: list[str] = Field(
        default_factory=list, description="Tools the agent called, in call order."
    )
    session_id: str = Field(description="Echoed back so the client can continue the thread.")
    sources: list[str] = Field(
        default_factory=list, description="Knowledge-base article ids used, if any."
    )
    degraded: bool = Field(
        default=False,
        description="True when a dependency failed and the answer is a safe fallback.",
    )


class ErrorResponse(BaseModel):
    """A user-safe error body. Never contains internals."""

    error: str
    detail: str


class Invoice(BaseModel):
    """A single invoice line on a customer account."""

    invoice_id: str
    date: str
    amount: float
    status: Literal["paid", "unpaid", "refunded"]


class Customer(BaseModel):
    """The canonical customer record returned by the internal backend."""

    customer_id: str
    name: str
    email: str
    subscription: Literal["Starter", "Pro", "Enterprise"]
    monthly_price: float
    currency: str = "USD"
    outstanding_balance: float
    renewal_date: str
    account_status: Literal["active", "past_due", "cancelled"]
    signup_date: str
    seats: int
    payment_method: str
    recent_invoices: list[Invoice] = Field(default_factory=list)


class SubscriptionDetails(BaseModel):
    """Subscription-only projection of a customer record."""

    customer_id: str
    subscription: str
    monthly_price: float
    currency: str
    seats: int
    renewal_date: str
    account_status: str


class BillingInformation(BaseModel):
    """Billing-only projection of a customer record."""

    customer_id: str
    outstanding_balance: float
    currency: str
    payment_method: str
    account_status: str
    recent_invoices: list[Invoice] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Liveness/readiness payload."""

    status: Literal["ok", "degraded"]
    version: str
    llm_configured: bool
    knowledge_base_documents: int
    customers_loaded: int
